% -------------------------------------------------------------------
%  Generated by MATLAB on 28-May-2018 22:14:13
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

t2_54 = saveVarsMat.t2_54; % <6x693 double> too many elements

clear saveVarsMat;
